name: batman
version: 1.0.7
homepage: https://github.com/noojee/batman
description: A System Integrity Monitor for PCI DSS compliance. batman provides file integrity monitoring and log scanners with a built in scheduler suitable for use in a docker container.
repository: https://github.com/noojee/batman
environment: 
  sdk: '>=2.14.4 <3.0.0'
dependencies: 
  args: ^2.3.0
  checked_yaml: ^2.0.1
  collection: ^1.15.0
  completer_ex: ^3.0.0
  crclib: ^3.0.0
  cron: ^0.4.0
  crypto: ^3.0.1
  dcli: ^1.15.5
  dcli_core: ^0.0.5
  hive: ^2.0.4
  intl: ^0.17.0
  json_annotation: ^4.3.0
  mailer: ^5.0.2
  meta: ^1.7.0
  posix: ^3.0.0
  recase: ^4.0.0
  settings_yaml: ^3.2.0
  system_info: ^1.0.1
  test: ^1.19.3
  yaml: ^3.1.0
  zone_di2: ^2.0.0
dev_dependencies: 
  build_runner: ^2.1.5
  dcli_scripts: ^1.1.7
  hive_generator: ^1.1.1
  json_serializable: ^6.0.1
  lint_hard: ^1.0.3
executables: 
  batman: batman
