name: pci_file_monitor
version: 1.0.0
homepage: https://github.com/noojee/pci_file_monitor
description: A File Integrity Monitor for PCI DSS compliance.
  pcifim can create a baseline of your file system and then scan
  for changes on a scheduled basis.
repository: https://github.com/noojee/pci_file_monitor
environment: 
  sdk: '>=2.14.4 <3.0.0'
dependencies: 
  args: ^2.3.0
  cron: ^0.4.0
  dcli: ^1.13.0
  dcli_core: ^0.0.2
  intl: ^0.17.0
  mailer: ^5.0.2
  settings_yaml: ^3.2.0
  test: ^1.19.3
dev_dependencies: 
  lints: ^1.0.0

# dependency_overrides:
#   dcli:
#     path: ../dcli
#   dcli_core:
#     path: ../dcli_core
