name: batman
version: 1.0.8
homepage: https://github.com/noojee/batman
description: A System Integrity Monitor for PCI DSS compliance. batman provides file integrity monitoring and log scanners with a built in scheduler suitable for use in a docker container.
repository: https://github.com/noojee/batman
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  args: ^2.3.0
  checked_yaml: ^2.0.1
  collection: ^1.15.0
  completer_ex: ^4.0.0
  crclib: ^3.0.0
  cron: ^0.5.1
  crypto: ^3.0.1
  dcli: ^1.15.5
  dcli_core: ^0.0.5
  hive: ^2.0.4
  intl: ^0.18.1
  json_annotation: ^4.3.0
  mailer: ^6.0.1
  meta: ^1.7.0
  posix: ^3.0.0
  recase: ^4.0.0
  settings_yaml: ^3.2.0
  system_info: ^1.0.1
  test: ^1.19.3
  yaml: ^3.1.0
  zone_di2: ^2.0.0
dev_dependencies: 
  build_runner: ^2.1.5
  dcli_scripts: ^1.1.7
  hive_generator: ^2.0.0
  json_serializable: ^6.0.1
  lint_hard: ^4.0.0
executables: 
  batman: batman
