name: pci_file_monitor
version: 1.0.0
homepage: https://github.com/noojee/pci_file_monitor
description: A File Integrity Monitor for PCI DSS compliance.
  pcifim can create a baseline of your file system and then scan
  for changes on a scheduled basis.
repository: https://github.com/noojee/pci_file_monitor
environment: 
  sdk: '>=2.14.4 <3.0.0'
dependencies: 
  args: ^2.3.0
  
  checked_yaml: ^2.0.1
  cron: ^0.4.0
  dcli: ^1.13.0
  dcli_core: ^0.0.2
  intl: ^0.17.0
  json_annotation: ^4.3.0
  
  mailer: ^5.0.2
  meta: ^1.7.0
  recase: ^4.0.0
  settings_yaml: ^3.2.0
  system_info: ^1.0.1
  test: ^1.19.3
dev_dependencies: 
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  lints: ^1.0.0

dependency_overrides:
  settings_yaml:
    path: ../settings_yaml
#   dcli:
#     path: ../dcli
#   dcli_core:
#     path: ../dcli_core
