name: pci_file_monitor
version: 1.0.0
homepage: https://github.com/noojee/pci_file_monitor
description: A simple command-line application.
repository: https://github.com/noojee/pci_file_monitor
environment: 
  sdk: '>=2.14.4 <3.0.0'
dependencies: 
  dcli: ^1.12.0
  mailer: ^5.0.2
  settings_yaml: ^3.2.0
  test: ^1.19.3
dev_dependencies: 
  lints: ^1.0.0
