version: '3.1'

volumes:
  batman_hive: null
  batman_etc: null

services:
  batman:
    container_name: batman
    image: noojee/batman:latest
    restart: on-failure
    environment:
      TZ: ${TZ:-Australia/Melbourne}
    volumes:
     - batman_hive:/data/hive       
     - batman_etc:/etc/batman  
     - /:/scandir:ro
    logging:
      #driver: "local"
      driver: "journald"      

      